export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const ACTIVE_FILTER_UPDATE = 'ACTIVE_FILTER_UPDATE';
export const UPDATE_SLIDER_VALUE = 'UPDATE_SLIDER_VALUE';

export const UPDATE_IMAGE_DIRECTIONS= 'UPDATE_IMAGE_DIRECTIONS';

export const RESET_FILTERS = 'RESET_FILTERS';
